---

name: igorlabs-jellyfin

services:
  jellyfin:
    container_name: jellyfin
    image: ghcr.io/jellyfin/jellyfin:latest
    restart: unless-stopped
    network_mode: host
    volumes:
      - /DATA/AppData/_jellyfin/config:/config
      - /DATA/AppData/_jellyfin/cache:/cache
      - /mnt/exthd/media:/media
    devices:
      - /dev/dri:/dev/dri

x-casaos:
  architectures:
    - amd64
    - arm64
  main: jellyfin
  developer: jellyfin.org
  category: Streaming
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/jellyfin.png
  index: /
  port_map: "8096"
  scheme: http
  title:
    custom: Jellyfin
