---

name: igorlabs-metube

services:
  metube:
    container_name: metube
    image: ghcr.io/alexta69/metube:latest
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 8081:8081
    volumes:
      - /DATA/Downloads:/downloads
    environment:
      - UID=1000
      - GID=1000
      - CUSTOM_DIRS=false

x-casaos:
  architectures:
    - amd64
    - arm64
  main: metube
  developer: alexta69
  category: Downloads
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/metube.png
  index: /
  port_map: "8081"
  scheme: http
  title:
    custom: MeTube
