---
name: igorlabs-paperless
networks:
  paperless_net:
    external: true
    name: paperless_net
services:
  paperless_app:
    container_name: paperless_app
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    deploy:
      resources:
        limits:
          memory: 2G
    stop_grace_period: 5m
    restart: unless-stopped
    depends_on:
      - paperless_database
      - paperless_broker
      - paperless_gotenberg
      - paperless_tika
    networks:
      - paperless_net
    ports:
      - 8000:8000
    volumes:
      - /DATA/AppData/$AppID/usr/src/paperless/data:/usr/src/paperless/data
      - /DATA/AppData/$AppID/usr/src/paperless/media:/usr/src/paperless/media
      - /DATA/AppData/$AppID/usr/src/paperless/export:/usr/src/paperless/export
      - /DATA/AppData/$AppID/usr/src/paperless/consume:/usr/src/paperless/consume
    environment:
      - PAPERLESS_REDIS=redis://paperless_broker:6379
      - PAPERLESS_DBHOST=paperless_database
      - PAPERLESS_TIKA_ENABLED=1
      - PAPERLESS_TIKA_GOTENBERG_ENDPOINT=http://paperless_gotenberg:3000
      - PAPERLESS_TIKA_ENDPOINT=http://paperless_tika:9998
      - PAPERLESS_TIME_ZONE=$TZ
      - PAPERLESS_OCR_LANGUAGE=eng
      - PAPERLESS_OCR_LANGUAGEs=por
  paperless_database:
    container_name: paperless_database
    image: postgres:latest
    deploy:
      resources:
        limits:
          memory: 2G
    stop_grace_period: 5m
    restart: unless-stopped
    networks:
      - paperless_net
    volumes:
      - /DATA/AppData/$AppID/var/lib/postgresql/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=paperless
      - POSTGRES_USER=paperless
      - POSTGRES_PASSWORD=paperless
  paperless_broker:
    container_name: paperless_broker
    image: redis:latest
    deploy:
      resources:
        limits:
          memory: 2G
    stop_grace_period: 5m
    restart: unless-stopped
    networks:
      - paperless_net
    volumes:
      - /DATA/AppData/$AppID/data:/data
    command:
      - redis-server
      - --save 60 1
      - --loglevel warning
  paperless_gotenberg:
    container_name: paperless_gotenberg
    image: gotenberg/gotenberg:latest
    deploy:
      resources:
        limits:
          memory: 2G
    stop_grace_period: 5m
    restart: unless-stopped
    networks:
      - paperless_net
    command:
      - gotenberg
      - --chromium-disable-javascript=true
      - --chromium-allow-list=file:///tmp/.*
  paperless_tika:
    container_name: paperless_tika
    image: apache/tika:latest
    deploy:
      resources:
        limits:
          memory: 2G
    stop_grace_period: 5m
    restart: unless-stopped
    networks:
      - paperless_net
x-casaos:
  architectures:
    - amd64
    - arm64
  main: paperless_app
  developer: docs.paperless-ngx.com
  category: Document Management
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/paperless-ngx.png
  index: /
  port_map: "8000"
  scheme: http
  title:
    custom: Paperless-ngx
    en_us: Paperless-ngx
