---
name: igorlabs-lidarr
networks:
  arr_net:
    external: true
    name: arr_net
services:
  lidarr:
    container_name: lidarr
    image: lscr.io/linuxserver/lidarr:latest
    deploy:
      resources:
        limits:
          memory: 2G
    stop_grace_period: 5m
    restart: unless-stopped
    networks:
      - arr_net
    ports:
      - 8686:8686
    volumes:
      - /DATA/AppData/$AppID/config:/config
      - /DATA/Media:/media
    environment:
      - TZ=$TZ
      - PUID=$PUID
      - PGID=$PGID
x-casaos:
  architectures:
    - amd64
    - arm64
  main: lidarr
  developer: lidarr.audio
  category: Music
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/lidarr.png
  index: /
  port_map: "8686"
  scheme: http
  title:
    custom: Lidarr
    en_us: Lidarr
