---

name: _diun

services:
  diun:
    container_name: diun
    image: ghcr.io/crazy-max/diun:latest
    restart: unless-stopped
    network_mode: bridge
    volumes:
      - /DATA/AppData/_diun/data:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    env_file: /DATA/AppData/_diun/env
    command:
      - serve

x-casaos:
  architectures:
    - amd64
    - arm64
  main: diun
  developer: crazymax.dev
  category: Updates
  hostname: crazymax.dev
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/diun.png
  index: /diun
  port_map: ""
  scheme: https
  title:
    custom: Diun
