---

name: igorlabs-diun

services:
  diun:
    container_name: diun
    image: ghcr.io/crazy-max/diun:latest
    restart: unless-stopped
    network_mode: bridge
    volumes:
      - /DATA/AppData/igorlabs-diun/data:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    env_file:
      - /DATA/AppData/igorlabs-diun/diun.env
    command:
      - serve
    deploy:
      resources:
        limits:
          memory: 2G

x-casaos:
  architectures:
    - amd64
    - arm64
  main: diun
  developer: crazymax.dev
  category: Updates
  hostname: crazymax.dev
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/diun.png
  index: /diun
  port_map: ""
  scheme: https
  title:
    custom: Diun
    en_us: Diun
