---

name: igorlabs-romm

networks:
  romm_net:
    name: romm_net
    external: true

services:
  romm_app:
    container_name: romm_app
    image: rommapp/romm:latest
    restart: unless-stopped
    networks:
      - romm_net
    ports:
      - 6060:8080
    depends_on:
      - romm_database
    environment:
      - DB_HOST=romm_database
      - DB_NAME=romm
      - DB_USER=romm
      - DB_PASSWD=romm
    env_file:
      - /DATA/AppData/_romm/romm_app.env
    volumes:
      - /DATA/AppData/_romm/redis-data:/redis-data
      - /DATA/AppData/_romm/romm/config:/romm/config
      - /DATA/AppData/_romm/romm/resources:/romm/resources
      - /DATA/AppData/_romm/romm/assets:/romm/assets
      - /DATA/AppData/_romm/romm/library:/romm/library
    deploy:
      resources:
        limits:
          memory: 2G

  romm_database:
    container_name: romm_database
    image: mariadb:lts
    restart: unless-stopped
    networks:
      - romm_net
    volumes:
      - /DATA/AppData/_romm/var/lib/mysql:/var/lib/mysql
    environment:
      - MARIADB_AUTO_UPGRADE=1
      - MARIADB_ROOT_PASSWORD=insecure
      - MARIADB_DATABASE=romm
      - MARIADB_USER=romm
      - MARIADB_PASSWORD=romm
    command:
      - --innodb-buffer-pool-size=512M
      - --transaction-isolation=READ-COMMITTED
      - --log-bin=binlog
      - --binlog-format=ROW
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    deploy:
      resources:
        limits:
          memory: 2G

x-casaos:
  architectures:
    - amd64
    - arm64
  main: romm_app
  developer: romm.app
  category: Games
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/romm.png
  index: /
  port_map: "6060"
  scheme: http
  title:
    custom: RomM
