---

name: _romm

networks:
  romm_net:
    name: romm_net
    external: true

services:
  romm_app:
    # Descrição: Aplicação RomM para gerenciamento de ROMs e jogos
    container_name: romm_app
    image: rommapp/romm:latest
    restart: unless-stopped
    networks:
      - romm_net
    ports:
      - 6060:8080
    depends_on:
      - romm_database
    environment:
      - ENABLE_SCHEDULED_RESCAN=true # Habilita a revarredura agendada
      - ENABLE_RESCAN_ON_FILESYSTEM_CHANGE=true # Habilita a revarredura ao detectar mudanças no sistema de arquivos
      - ROMM_DB_DRIVER=mariadb # Driver do banco de dados. Padrão: mariadb
      - DB_HOST=romm_database # Host do banco de dados. Padrão: romm_database
      - DB_NAME=${DB_NAME:-romm} # Nome do banco de dados. Padrão: romm
      - DB_USER=${DB_USER:-romm} # Nome do usuário do banco de dados. Padrão: romm
      - DB_PASSWD=${DB_PASS:-romm} # Senha do usuário do banco de dados. Padrão: romm
      - ROMM_AUTH_SECRET_KEY=${AUTH_KEY} # Chave secreta para autenticação. Gerar com o comando `openssl rand -base64 32`
      - KIOSK_MODE=false # Modo quiosque. Padrão: false
      - TZ=${TZ:-America/Sao_Paulo} # Fuso horário. Padrão: America/Sao_Paulo
      - HASHEOUS_API_ENABLED=true # Habilita a API do Hasheous
    volumes:
      - /DATA/AppData/$AppID/redis-data:/redis-data # Volume para dados do Redis
      - /DATA/AppData/$AppID/romm/config:/romm/config # Volume para configuração do RomM
      - /DATA/AppData/$AppID/romm/resources:/romm/resources # Volume para recursos do RomM
      - /DATA/AppData/$AppID/romm/assets:/romm/assets # Volume para assets do RomM
      - /DATA/AppData/$AppID/romm/library:/romm/library # Volume para a biblioteca do RomM
  romm_database:
    # Descrição: Banco de dados MariaDB para o RomM
    container_name: romm_database
    image: lscr.io/linuxserver/mariadb:latest
    restart: unless-stopped
    networks:
      - romm_net
    volumes:
      - /DATA/AppData/$AppID/config:/config # Volume para configuração do banco de dados
    environment:
      - TZ=${TZ:-America/Sao_Paulo} # Fuso horário. Padrão: America/Sao_Paulo
      - PUID=${PUID:-1000} # ID do usuário. Padrão: 1000
      - PGID=${PGID:-1000} # ID do grupo. Padrão: 1000
      - MYSQL_ROOT_PASSWORD=${DB_ROOT:-insecure} # Senha do usuário root do banco de dados. Padrão: insecure
      - MYSQL_DATABASE=${DB_NAME:-romm} # Nome do banco de dados. Padrão: romm
      - MYSQL_USER=${DB_USER:-romm} # Nome do usuário do banco de dados. Padrão: romm
      - MYSQL_PASSWORD=${DB_PASS:-romm} # Senha do usuário do banco de dados. Padrão: romm

x-casaos:
  architectures:
    - amd64
    - arm64
  main: romm_app
  developer: romm.app
  category: Games
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/romm.png
  index: /
  port_map: "6060"
  scheme: http
  title:
    custom: RomM
