---

name: igorlabs-manyfold

services:
  manyfold:
    container_name: manyfold
    image: ghcr.io/manyfold3d/manyfold-solo:latest
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 3214:3214
    volumes:
      - /DATA/AppData/_manyfold/config:/config
      - /DATA/AppData/_manyfold/models:/models
    environment:
      - PUID=1000
      - PGID=1000
    env_file:
      - /DATA/AppData/_manyfold/manyfold.env

x-casaos:
  architectures:
    - amd64
    - arm64
  main: manyfold
  developer: manyfold.app
  category: 3D Printing
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/manyfold.png
  index: /
  port_map: "3214"
  scheme: http
  title:
    custom: Manyfold
