---

name: igorlabs-manyfold

networks:
  manyfold_net:
    name: manyfold_net
    external: true

services:
  manyfold_app:
    container_name: manyfold_app
    image: ghcr.io/manyfold3d/manyfold:latest
    restart: unless-stopped
    networks:
      - manyfold_net
    ports:
      - 3214:3214
    depends_on:
      - manyfold_database
      - manyfold_broker
    volumes:
      - /DATA/AppData/_manyfold/models:/models
    environment:
      - PUID=1000
      - PGID=1000
      - DATABASE_HOST=manyfold_database
      - DATABASE_NAME=manyfold
      - DATABASE_USER=manyfold
      - DATABASE_PASSWORD=manyfold
      - REDIS_URL=redis://manyfold_broker:6379/1
    env_file:
      - /DATA/AppData/_manyfold/manyfold.env
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - SETUID
      - SETGID

  manyfold_database:
    container_name: manyfold_database
    image: postgres:latest
    restart: unless-stopped
    networks:
      - manyfold_net
    volumes:
      - /DATA/AppData/_manyfold/var/lib/postgresql/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=manyfold
      - POSTGRES_USER=manyfold
      - POSTGRES_PASSWORD=manyfold

  manyfold_broker:
    container_name: manyfold_broker
    image: redis:latest
    restart: unless-stopped
    networks:
      - manyfold_net
    volumes:
      - /DATA/AppData/_manyfold/data:/data
    command:
      - redis-server
      - --save 60 1
      - --loglevel warning

x-casaos:
  architectures:
    - amd64
    - arm64
  main: manyfold_app
  developer: manyfold.app
  category: 3D Printing
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/manyfold.png
  index: /
  port_map: "3214"
  scheme: http
  title:
    custom: Manyfold
