---

name: igorlabs-prowlarr

networks:
  servarr_net:
    name: servarr_net
    external: true

services:
  prowlarr:
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr:latest
    restart: unless-stopped
    networks:
      - servarr_net
    ports:
      - 9696:9696
    volumes:
      - /DATA/AppData/_prowlarr/config:/config
    environment:
      - TZ=America/Sao_Paulo
      - PUID=1000
      - PGID=1000

x-casaos:
  architectures:
    - amd64
    - arm64
  main: prowlarr
  developer: prowlarr.com
  category: Downloads
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/prowlarr.png
  index: /
  port_map: "9696"
  scheme: http
  title:
    custom: Prowlarr
