---
name: igorlabs-bazarr
networks:
  arr_net:
    external: true
    name: arr_net
services:
  bazarr:
    container_name: bazarr
    image: lscr.io/linuxserver/bazarr:latest
    deploy:
      resources:
        limits:
          memory: 2G
    stop_grace_period: 5m
    restart: unless-stopped
    networks:
      - arr_net
    ports:
      - 6767:6767
    volumes:
      - /DATA/AppData/$AppID/config:/config
      - /mnt/exthd/data:/data
    environment:
      - TZ=$TZ
      - PUID=$PUID
      - PGID=$PGID
x-casaos:
  architectures:
    - amd64
    - arm64
  main: bazarr
  developer: bazarr.media
  category: Subtitles
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/bazarr.png
  index: /
  port_map: "6767"
  scheme: http
  title:
    custom: Bazarr
    en_us: Bazarr
