---

name: igorlabs-glances

services:
  glances:
    container_name: glances
    image: nicolargo/glances:latest-full
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/os-release:/etc/os-release:ro
    environment:
      - TZ=America/Sao_Paulo
      - GLANCES_OPT=-w

x-casaos:
  architectures:
    - amd64
    - arm64
  main: glances
  developer: nicolargo.github.io
  category: Monitoring
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/glances.png
  index: /
  port_map: "61208"
  scheme: http
  title:
    custom: Glances
    en_us: Glances
